### ISSUE TITLE
Browsertrix Preprocessor ToDo

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/integrity-preprocessor#5]
- [x] rename wacz file in zip to sha256(wacz).wacz
- [x] Lambda sort at around 210 fails when item is not finished since there is no date/time
- [ ] https://github.com/starlinglab/starling-integrity-preprocessor/pull/3#discussion_r845489662
- [ ] https://github.com/starlinglab/starling-integrity-preprocessor/pull/3#discussion_r845491478
- [x] HOST->URL Rename in #11 (source: https://github.com/starlinglab/starling-integrity-preprocessor/pull/3#discussion_r845485298 )
